// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
//  import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiP5iPTw3Otfatw2HNT_-UUa2lCSK5N78',
    appId: '1:509573428630:web:46be5c26a37263a03799b7',
    messagingSenderId: '509573428630',
    projectId: 'community-app-c1b2b',
    authDomain: 'community-app-c1b2b.firebaseapp.com',
    databaseURL: 'https://community-app-c1b2b-default-rtdb.firebaseio.com',
    storageBucket: 'community-app-c1b2b.appspot.com',
    measurementId: 'G-DFRKBZP0GE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlOsl3atjFpvoFZJoO7N7F34sMTMJ8le4',
    appId: '1:509573428630:android:0cf95703958bedeb3799b7',
    messagingSenderId: '509573428630',
    projectId: 'community-app-c1b2b',
    databaseURL: 'https://community-app-c1b2b-default-rtdb.firebaseio.com',
    storageBucket: 'community-app-c1b2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7Un7Q-7kCHkdZ5o91yHIL0ngv6s_-YCI',
    appId: '1:509573428630:ios:ff4dafdec4f24b143799b7',
    messagingSenderId: '509573428630',
    projectId: 'community-app-c1b2b',
    databaseURL: 'https://community-app-c1b2b-default-rtdb.firebaseio.com',
    storageBucket: 'community-app-c1b2b.appspot.com',
    iosBundleId: 'com.jdshah.communityApp',
  );
}
